#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 07, 2018 03:00:18 PM

# -----------------------------------------------------------------------------
# IMPORTS
# -----------------------------------------------------------------------------
# import sys
import os
import Imreg.Methods as Met
import Imreg.RegistrationMethods as Reg
from tkinter.filedialog import askopenfilename
import time

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Regim_page_support


# -----------------------------------------------------------------------------
# EXTRA METHODS
# -----------------------------------------------------------------------------
def vp_start_gui():
    """Starting point when module is the main routine."""
    global val, w, root
    root = Tk()
    top = Regim(root)
    Regim_page_support.init(root, top)
    root.mainloop()


w = None


def create_regim(root, *args, **kwargs):
    """Starting point when module is imported by another program."""
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = Regim(w)
    Regim_page_support.init(w, top, *args, **kwargs)
    return w, top


def destroy_regim():
    global w
    w.destroy()
    w = None


def exit_btn():
    """Close program"""
    root.quit()
    root.destroy()
    exit()


# -----------------------------------------------------------------------------
# GLOBAL VARIABLES
# -----------------------------------------------------------------------------
my_icon = 'images/icono.ico'
my_imref_path = ''
my_iminput_path = ''
my_add_btn_path = 'images/add_btn.png'
my_empty_image_path = 'images/empty.jpg'
my_png_dest_1 = 'input_1.png'
my_png_dest_2 = 'input_2.png'

in_size = 200, 200
out_size = 400, 400
# -----------------------------------------------------------------------------
# MAIN CLASS
# -----------------------------------------------------------------------------

class Regim:

    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
                top is the toplevel containing window."""

        from PIL import ImageTk, Image

        # Loading required images and paths
        self.icon_path = Met.resource_path(my_icon)
        self.imref_path = None
        self.iminput_path = None
        self.add_btn_path = Met.resource_path(my_add_btn_path)
        self.empty_image_path = Met.resource_path(my_empty_image_path)
        self.png_dest_1 = my_png_dest_1
        self.png_dest_2 = my_png_dest_2

        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'
        font10 = "-family Verdana -size 10 -weight normal -slant roman"  \
            " -underline 0 -overstrike 0"
        font9 = "-family Verdana -size 13 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        # Opening and resizing images
        self.empty_image = Image.open(self.empty_image_path)
        self.empty_image.thumbnail(in_size, Image.ANTIALIAS)
        self.empty_image = ImageTk.PhotoImage(self.empty_image)

        self.empty_image2 = Image.open(self.empty_image_path)
        self.empty_image2.thumbnail(out_size, Image.ANTIALIAS)
        self.empty_image2 = ImageTk.PhotoImage(self.empty_image2)

        # Creating all the GUI
        top.geometry("975x610+127+8")
        top.title("Regim")
        top.iconbitmap(self.icon_path)
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.menubar = Menu(top, font="TkMenuFont")
        top.configure(menu=self.menubar)

        self.file = Menu(top, tearoff=0)
        self.menubar.add_cascade(
            menu=self.file,
            font="TkMenuFont",
            label="File"
        )
        self.file.add_command(
            font="TkMenuFont",
            command=self.open_file,
            label="Load"
        )
        self.file.add_command(
            font="TkMenuFont",
            label="Exit",
            command=exit_btn
        )

        self.help = Menu(top, tearoff=0)

        self.menubar.add_cascade(
            menu=self.help,
            activebackground="#d9d9d9",
            activeforeground="#000000",
            background="#d9d9d9",
            font="TkMenuFont",
            foreground="#000000",
            label="Help"
        )
        self.help.add_command(
            activebackground="#d8d8d8",
            activeforeground="#000000",
            background="#d9d9d9",
            font="TkMenuFont",
            foreground="#000000",
            label="About"
        )

        self.frame_side = Frame(top)
        self.frame_side.place(relx=-0.02, rely=-0.02, relheight=1.01, relwidth=0.22)
        self.frame_side.configure(relief=SUNKEN)
        self.frame_side.configure(borderwidth="1")
        self.frame_side.configure(relief=SUNKEN)
        self.frame_side.configure(background="#383838")
        self.frame_side.configure(highlightbackground="#ffffff")
        self.frame_side.configure(highlightcolor="black")
        self.frame_side.configure(width=215)

        self.btn_match = Button(self.frame_side)
        self.btn_match.place(relx=0.16, rely=0.87, height=34, width=150)
        self.btn_match.configure(activebackground="#c55050")
        self.btn_match.configure(activeforeground="white")
        self.btn_match.configure(activeforeground="#ffffff")
        self.btn_match.configure(background="#ff6b6b")
        self.btn_match.configure(borderwidth="0")
        self.btn_match.configure(disabledforeground="#a3a3a3")
        self.btn_match.configure(font=font9)
        self.btn_match.configure(foreground="#ffffff")
        self.btn_match.configure(highlightbackground="#d9d9d9")
        self.btn_match.configure(highlightcolor="black")
        self.btn_match.configure(overrelief="sunken")
        self.btn_match.configure(pady="0")
        self.btn_match.configure(relief=FLAT)
        self.btn_match.configure(text='Registration')

        self.label_side = LabelFrame(self.frame_side)
        self.label_side.place(relx=0.16, rely=0.05, relheight=0.79, relwidth=0.7)

        self.label_side.configure(borderwidth="1")
        self.label_side.configure(foreground="black")
        self.label_side.configure(relief=FLAT)
        self.label_side.configure(background="#585858")
        self.label_side.configure(width=150)

        self.frame_process = Frame(top)
        self.frame_process.place(relx=0.18, rely=0.02, relheight=1.02, relwidth=0.83)
        self.frame_process.configure(borderwidth="1")
        self.frame_process.configure(background="#cccccc")
        self.frame_process.configure(highlightbackground="#000000")
        self.frame_process.configure(highlightcolor="#ffffff")
        self.frame_process.configure(width=805)

        self.label_ref = Label(self.frame_process)
        self.label_ref.place(relx=0.06, rely=0.09, height=200, width=200)
        self.label_ref.configure(background="#ffffff")
        self.label_ref.configure(disabledforeground="#a3a3a3")
        self.label_ref.configure(font=font10)
        self.label_ref.configure(foreground="#000000")
        self.label_ref.configure(text='''Reference image''')
        self.label_ref.configure(width=200)
        self.label_ref.configure(image=self.empty_image)
        self.label_ref.image = self.empty_image

        self.label_input = Label(self.frame_process)
        self.label_input.place(relx=0.06, rely=0.48, height=200, width=200)
        self.label_input.configure(activebackground="#f9f9f9")
        self.label_input.configure(activeforeground="black")
        self.label_input.configure(background="#ffffff")
        self.label_input.configure(cursor="")
        self.label_input.configure(disabledforeground="#a3a3a3")
        self.label_input.configure(font=font10)
        self.label_input.configure(foreground="#000000")
        self.label_input.configure(highlightbackground="#d9d9d9")
        self.label_input.configure(highlightcolor="black")
        self.label_input.configure(text='''Input image''')
        self.label_input.configure(image=self.empty_image)
        self.label_input.image = self.empty_image

        self.label_reg = Label(self.frame_process)
        self.label_reg.place(relx=0.41, rely=0.12, height=400, width=400)
        self.label_reg.configure(background="#ffffff")
        self.label_reg.configure(disabledforeground="#a3a3a3")
        self.label_reg.configure(foreground="#000000")
        self.label_reg.configure(width=400)
        self.label_reg.configure(image=self.empty_image2)
        self.label_reg.image = self.empty_image2

        self.frame_foot = Frame(top)
        self.frame_foot.place(relx=-0.01, rely=0.94, relheight=0.07, relwidth=1.02)
        self.frame_foot.configure(relief=SUNKEN)
        self.frame_foot.configure(borderwidth="1")
        self.frame_foot.configure(relief=SUNKEN)
        self.frame_foot.configure(background="#383838")
        self.frame_foot.configure(highlightbackground="#d9d9d9")
        self.frame_foot.configure(highlightcolor="#ffffff")
        self.frame_foot.configure(width=995)

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=-0.01, rely=-0.1, relheight=0.14, relwidth=1.03)
        self.Frame1.configure(relief=RIDGE)
        self.Frame1.configure(borderwidth="1")
        self.Frame1.configure(relief=RIDGE)
        self.Frame1.configure(background="#383838")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#ffffff")
        self.Frame1.configure(width=1005)

        self.add1_button = Button(self.frame_process)
        self.add1_button.place(relx=0.32, rely=0.09, height=20, width=20)
        self.add1_button.configure(activebackground="#d9d9d9")
        self.add1_button.configure(activeforeground="#000000")
        self.add1_button.configure(background="#d9d9d9")
        self.add1_button.configure(borderwidth="0")
        self.add1_button.configure(disabledforeground="#a3a3a3")
        self.add1_button.configure(foreground="#000000")
        self.add1_button.configure(highlightbackground="#d9d9d9")
        self.add1_button.configure(highlightcolor="black")
        self._img1 = PhotoImage(file=self.add_btn_path)
        self.add1_button.configure(image=self._img1)
        self.add1_button.configure(pady="0")
        self.add1_button.configure(text='')
        self.add1_button.configure(width=350)
        self.add1_button.configure(command=self.add_ref_image)

        self.add2_button = Button(self.frame_process)
        self.add2_button.place(relx=0.32, rely=0.48, height=20, width=20)
        self.add2_button.configure(activebackground="#d9d9d9")
        self.add2_button.configure(activeforeground="#000000")
        self.add2_button.configure(background="#d9d9d9")
        self.add2_button.configure(borderwidth="0")
        self.add2_button.configure(disabledforeground="#a3a3a3")
        self.add2_button.configure(foreground="#000000")
        self.add2_button.configure(highlightbackground="#d9d9d9")
        self.add2_button.configure(highlightcolor="black")
        self._img2 = PhotoImage(file=self.add_btn_path)
        self.add2_button.configure(image=self._img2)
        self.add2_button.configure(pady="0")
        self.add2_button.configure(text='')
        self.add2_button.configure(command=self.add_in_image)

        self.btn_match.configure(command=self.do_registration)

    def open_file(self):
        """Open a file"""
        try:
            path = askopenfilename(initialdir=".",
                                   filetypes=(("Image File .jpg", "*.jpg"), ("All Files", "*.*")),
                                   title="Choose an imgage."
                                   )
        except():
            pass

    def do_match(self):
        """Method used for match characteristics elements between two images"""
        from PIL import ImageTk, Image

        try:
            images_matched = Met.match(self.imref_path, self.iminput_path)

            image_matched = Image.fromarray(images_matched)
            image_matched.thumbnail(out_size, Image.ANTIALIAS)
            image_matched = ImageTk.PhotoImage(image_matched)

            self.label_reg.configure(image=image_matched)
            self.label_reg.image = image_matched

            # os.remove(self.imref_path)
            # os.remove(self.iminput_path)
        except:
            pass

    def add_ref_image(self):
        """Open an image file and show it in the GUI"""
        from PIL import ImageTk, Image
        self.png_dest_1 = my_png_dest_1
        # Searching file
        try:
            self.imref_path = askopenfilename(
                        initialdir=".",
                        filetypes=(
                            ("Dicom (*.DCM)", "*.dcm"),
                            ("JPEG (*.JPG)", "*.jpg*"),
                            ("PNG (*.PNG)", "*.png*")
                        ),
                        title="Choose image 1."
                       )
            # Converting .dcm file to .png for manipulation
            if self.imref_path[-3:] == 'dcm':
                Met.dicom_to_png(self.imref_path, self.png_dest_1)
            else:
                self.png_dest_1 = self.imref_path

            # Place it in the GUI label
            png_file = Image.open(self.png_dest_1)
            png_file.thumbnail(in_size, Image.ANTIALIAS)
            png_image = ImageTk.PhotoImage(png_file)
            self.label_ref.configure(image=png_image)
            self.label_ref.image = png_image

            self.imref_path = self.png_dest_1

        except:
            pass

    def add_in_image(self):
        """Open an image file and show it in the GUI"""
        from PIL import ImageTk, Image
        self.png_dest_2 = my_png_dest_2
        try:
            # Searching file
            self.iminput_path = askopenfilename(
                            initialdir=".",
                            filetypes=(
                                ("Dicom (*.DCM)", "*.dcm"),
                                ("JPEG (*.JPG)", "*.jpg*"),
                                ("PNG (*.PNG)", "*.png*")
                            ),
                            title="Choose image 2."
                            )
            # Converting .dcm file to .png for manipulation
            if self.iminput_path[-3:] == 'dcm':
                Met.dicom_to_png(self.iminput_path, self.png_dest_2)
            else:
                self.png_dest_2 = self.iminput_path

            # Place it in the GUI label
            png_file = Image.open(self.png_dest_2)
            png_file.thumbnail(in_size, Image.ANTIALIAS)
            png_image = ImageTk.PhotoImage(png_file)
            self.label_input.configure(image=png_image)
            self.label_input.image = png_image

            self.iminput_path = self.png_dest_2

        except:
            pass

    def do_registration(self):
        """Do the registration for the fixed and moving image"""
        from PIL import Image, ImageTk
        try:
            my_imreg = Reg.Imreg(self.png_dest_1, self.png_dest_2)
            registered_image = my_imreg.image_registration_method3()
            # registered_image = Image.fromarray(self.registered_image)
            registered_image.thumbnail(out_size, Image.ANTIALIAS)
            registered_image.resize(out_size, Image.ANTIALIAS)
            registered_image = ImageTk.PhotoImage(registered_image)

            self.label_reg.configure(image=registered_image)
            self.label_reg.image = registered_image
        except:
            pass


if __name__ == '__main__':
    vp_start_gui()
